name: login_package
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1
  flutter_screen_recording: ^2.0.24
  http: ^1.0.0
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.1.0
  video_player: ^2.10.0
  dio: ^5.8.0+1
  # aws_s3_upload: ^1.5.0
  aws_signature_v4: ^0.6.5
  # flutter_ffmpeg: ^0.4.2
  flutter_background_service: ^5.1.0
  screen_recorder: ^0.3.0
  shared_preferences: ^2.5.3
  crypto: ^3.0.6
  convert: ^3.1.2
  aws_common: ^0.7.7
  intl: ^0.18.0
  flutter_dotenv: ^5.2.1
  equatable: ^2.0.7
  docx_file_viewer: ^0.0.7
  file_picker: ^10.2.0
  syncfusion_flutter_pdfviewer: ^30.1.41
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
